/* Copyright (C) 2014-2016 by Jacob Alexander
 *
 * This file is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this file.  If not, see <http://www.gnu.org/licenses/>.
 */

// This file was generated by the kll compiler, DO NOT EDIT.
// Generation Date:    2018-01-04
// KLL Emitter:        kiibohd
// KLL Version:        BETA 0.5c.dea946f21c8069342b7daaa17f68e791c6a10ffd - 2017-12-09 20:58:57 -0800
// KLL Git Changes:    None
// Compiler arguments:
//      ../../kll/kll
//    --kiibohd-debug
//    --config
//      /home/oliver/repos/ergodox/Scan/Devices/ISSILed/capabilities.kll
//      /home/oliver/repos/ergodox/Scan/Devices/MatrixARMPeriodic/capabilities.kll
//      /home/oliver/repos/ergodox/Scan/Devices/STLcd/capabilities.kll
//      /home/oliver/repos/ergodox/Scan/Devices/UARTConnect/capabilities.kll
//      /home/oliver/repos/ergodox/Macro/PartialMap/capabilities.kll
//      /home/oliver/repos/ergodox/Macro/PixelMap/capabilities.kll
//      /home/oliver/repos/ergodox/Output/HID-IO/capabilities.kll
//      /home/oliver/repos/ergodox/Output/USB/capabilities.kll
//      /home/oliver/repos/ergodox/Debug/latency/capabilities.kll
//    --base
//      /home/oliver/repos/ergodox/Scan/Infinity_Ergodox/scancode_map.kll
//      /home/oliver/repos/ergodox/Scan/Infinity_Ergodox/leftHand.kll
//      /home/oliver/repos/ergodox/Scan/Infinity_Ergodox/slave1.kll
//      /home/oliver/repos/ergodox/Scan/Infinity_Ergodox/rightHand.kll
//    --default
//      layer-default.kll
//      /home/oliver/repos/ergodox/kll/layouts/infinity_ergodox/lcdFuncMap.kll
//    --partial
//      layer-1.kll
//      /home/oliver/repos/ergodox/kll/layouts/infinity_ergodox/lcdFuncMap.kll
//    --emitter
//      kiibohd
//    --def-template
//      /home/oliver/repos/ergodox/kll/templates/kiibohdDefs.h
//    --map-template
//      /home/oliver/repos/ergodox/kll/templates/kiibohdKeymap.h
//    --pixel-template
//      /home/oliver/repos/ergodox/kll/templates/kiibohdPixelmap.c
//    --def-output
//      kll_defs.h
//    --map-output
//      generatedKeymap.h
//    --pixel-output
//      generatedPixelmap.c
//
// - Configuration File -
//    ISSILedCapabilities
//      /tmp/kll/_home_oliver_repos_ergodox_Scan_Devices_ISSILed@['capabilities']_processed.kll
//    MatrixARMPeriodicCapabilities
//      /tmp/kll/_home_oliver_repos_ergodox_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll
//    STLcdCapabilities
//      /tmp/kll/_home_oliver_repos_ergodox_Scan_Devices_STLcd@['capabilities']_processed.kll
//    UARTConnectCapabilities
//      /tmp/kll/_home_oliver_repos_ergodox_Scan_Devices_UARTConnect@['capabilities']_processed.kll
//    PartialMapCapabilities
//      /tmp/kll/_home_oliver_repos_ergodox_Macro_PartialMap@['capabilities']_processed.kll
//    PixelMapCapabilities
//      /tmp/kll/_home_oliver_repos_ergodox_Macro_PixelMap@['capabilities']_processed.kll
//    HID-IOCapabilities
//      /tmp/kll/_home_oliver_repos_ergodox_Output_HID-IO@['capabilities']_processed.kll
//    USBCapabilities
//      /tmp/kll/_home_oliver_repos_ergodox_Output_USB@['capabilities']_processed.kll
//    latency
//      /tmp/kll/_home_oliver_repos_ergodox_Debug_latency@['capabilities']_processed.kll
// - Generic Files -
// - Base Layer -
//    MDErgo1
//      /tmp/kll/_home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['scancode_map']_processed.kll
//    Infinity Ergodox Left Hand
//      /tmp/kll/_home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['leftHand']_processed.kll
//    MDErgo1Slave1
//      /tmp/kll/_home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['slave1']_processed.kll
//    Infinity Ergodox Right Hand
//      /tmp/kll/_home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['rightHand']_processed.kll
// - Default Layer -
//    MDErgo1
//      /tmp/kll/@['layer-default']_processed.kll
//    lcdFuncMap
//      /tmp/kll/_home_oliver_repos_ergodox_kll_layouts_infinity_ergodox@['lcdFuncMap']_processed.kll
// - Partial Layers -
//    Layer 1
//     MDErgo1
//       /tmp/kll/@['layer-1']_processed.kll
//     lcdFuncMap
//       /tmp/kll/_home_oliver_repos_ergodox_kll_layouts_infinity_ergodox@['lcdFuncMap']_processed.kll



#pragma once

// ----- Includes -----

// KLL Include
#include <kll.h>



// ----- Capabilities -----

// Capability function declarations
void LCD_layerStackExact_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void LCD_layerStack_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void LED_control_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_layerLatch_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_layerLock_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_layerRotate_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_layerShift_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Macro_layerState_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_consCtrlSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_flashMode_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_kbdProtocolBoot_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_kbdProtocolNKRO_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_noneSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_sysCtrlSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_toggleKbdProtocol_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_usbCodeSend_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Output_usbMouse_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_AnimationControl_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_AnimationIndex_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_Animation_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );
void Pixel_Pixel_capability( TriggerMacro *trigger, uint8_t state, uint8_t stateType, uint8_t *args );



// Indexed Capabilities Table
const Capability CapabilitiesList[] = {
	/* 0 LCDLayerDisplayExact */
	{ LCD_layerStackExact_capability, 9, CapabilityFeature_None },
	/* 1 LCDLayerDisplay */
	{ LCD_layerStack_capability, 0, CapabilityFeature_None },
	/* 2 ledControl */
	{ LED_control_capability, 2, CapabilityFeature_None },
	/* 3 layerLatch */
	{ Macro_layerLatch_capability, 2, CapabilityFeature_Safe },
	/* 4 layerLock */
	{ Macro_layerLock_capability, 2, CapabilityFeature_Safe },
	/* 5 layerRotate */
	{ Macro_layerRotate_capability, 1, CapabilityFeature_Safe },
	/* 6 layerShift */
	{ Macro_layerShift_capability, 2, CapabilityFeature_Safe },
	/* 7 layerState */
	{ Macro_layerState_capability, 3, CapabilityFeature_Safe },
	/* 8 consCtrlOut */
	{ Output_consCtrlSend_capability, 2, CapabilityFeature_Safe },
	/* 9 flashMode */
	{ Output_flashMode_capability, 0, CapabilityFeature_Safe },
	/* 10 kbdProtocolBoot */
	{ Output_kbdProtocolBoot_capability, 0, CapabilityFeature_None },
	/* 11 kbdProtocolNKRO */
	{ Output_kbdProtocolNKRO_capability, 0, CapabilityFeature_None },
	/* 12 noneOut */
	{ Output_noneSend_capability, 0, CapabilityFeature_Safe },
	/* 13 sysCtrlOut */
	{ Output_sysCtrlSend_capability, 1, CapabilityFeature_Safe },
	/* 14 toggleKbdProtocol */
	{ Output_toggleKbdProtocol_capability, 0, CapabilityFeature_None },
	/* 15 usbKeyOut */
	{ Output_usbCodeSend_capability, 1, CapabilityFeature_Safe },
	/* 16 mouseOut */
	{ Output_usbMouse_capability, 6, CapabilityFeature_Safe },
	/* 17 animation_control */
	{ Pixel_AnimationControl_capability, 1, CapabilityFeature_None },
	/* 18 animationIndex */
	{ Pixel_AnimationIndex_capability, 2, CapabilityFeature_None },
	/* 19 animation */
	{ Pixel_Animation_capability, 7, CapabilityFeature_None },
	/* 20 pixel */
	{ Pixel_Pixel_capability, 0, CapabilityFeature_None },
};


// -- Result Macros

// Result Macro Guides
Guide_RM( 0 ) = { 1, 8, 181, 0, 0 }; // (HID(ConsCode)"CONSUMER_SCAN_NEXT_TRACK")
Guide_RM( 1 ) = { 1, 8, 182, 0, 0 }; // (HID(ConsCode)"CONSUMER_SCAN_PREVIOUS_TRACK")
Guide_RM( 2 ) = { 1, 8, 205, 0, 0 }; // (HID(ConsCode)"CONSUMER_PAUSE_PLAY")
Guide_RM( 3 ) = { 1, 8, 226, 0, 0 }; // (HID(ConsCode)"CONSUMER_MUTE")
Guide_RM( 4 ) = { 1, 8, 233, 0, 0 }; // (HID(ConsCode)"CONSUMER_VOLUME_UP")
Guide_RM( 5 ) = { 1, 8, 234, 0, 0 }; // (HID(ConsCode)"CONSUMER_VOLUME_DOWN")
Guide_RM( 6 ) = { 1, 15, KEY_A, 0 }; // (HID(USBCode)"KEY_A")
Guide_RM( 7 ) = { 1, 15, KEY_B, 0 }; // (HID(USBCode)"KEY_B")
Guide_RM( 8 ) = { 1, 15, KEY_C, 0 }; // (HID(USBCode)"KEY_C")
Guide_RM( 9 ) = { 1, 15, KEY_D, 0 }; // (HID(USBCode)"KEY_D")
Guide_RM( 10 ) = { 1, 15, KEY_E, 0 }; // (HID(USBCode)"KEY_E")
Guide_RM( 11 ) = { 1, 15, KEY_F, 0 }; // (HID(USBCode)"KEY_F")
Guide_RM( 12 ) = { 1, 15, KEY_G, 0 }; // (HID(USBCode)"KEY_G")
Guide_RM( 13 ) = { 1, 15, KEY_H, 0 }; // (HID(USBCode)"KEY_H")
Guide_RM( 14 ) = { 1, 15, KEY_I, 0 }; // (HID(USBCode)"KEY_I")
Guide_RM( 15 ) = { 1, 15, KEY_J, 0 }; // (HID(USBCode)"KEY_J")
Guide_RM( 16 ) = { 1, 15, KEY_K, 0 }; // (HID(USBCode)"KEY_K")
Guide_RM( 17 ) = { 1, 15, KEY_L, 0 }; // (HID(USBCode)"KEY_L")
Guide_RM( 18 ) = { 1, 15, KEY_M, 0 }; // (HID(USBCode)"KEY_M")
Guide_RM( 19 ) = { 1, 15, KEY_N, 0 }; // (HID(USBCode)"KEY_N")
Guide_RM( 20 ) = { 1, 15, KEY_O, 0 }; // (HID(USBCode)"KEY_O")
Guide_RM( 21 ) = { 1, 15, KEY_P, 0 }; // (HID(USBCode)"KEY_P")
Guide_RM( 22 ) = { 1, 15, KEY_Q, 0 }; // (HID(USBCode)"KEY_Q")
Guide_RM( 23 ) = { 1, 15, KEY_R, 0 }; // (HID(USBCode)"KEY_R")
Guide_RM( 24 ) = { 1, 15, KEY_S, 0 }; // (HID(USBCode)"KEY_S")
Guide_RM( 25 ) = { 1, 15, KEY_T, 0 }; // (HID(USBCode)"KEY_T")
Guide_RM( 26 ) = { 1, 15, KEY_U, 0 }; // (HID(USBCode)"KEY_U")
Guide_RM( 27 ) = { 1, 15, KEY_V, 0 }; // (HID(USBCode)"KEY_V")
Guide_RM( 28 ) = { 1, 15, KEY_W, 0 }; // (HID(USBCode)"KEY_W")
Guide_RM( 29 ) = { 1, 15, KEY_X, 0 }; // (HID(USBCode)"KEY_X")
Guide_RM( 30 ) = { 1, 15, KEY_Y, 0 }; // (HID(USBCode)"KEY_Y")
Guide_RM( 31 ) = { 1, 15, KEY_Z, 0 }; // (HID(USBCode)"KEY_Z")
Guide_RM( 32 ) = { 1, 15, KEY_1, 0 }; // (HID(USBCode)"KEY_1")
Guide_RM( 33 ) = { 1, 15, KEY_2, 0 }; // (HID(USBCode)"KEY_2")
Guide_RM( 34 ) = { 1, 15, KEY_3, 0 }; // (HID(USBCode)"KEY_3")
Guide_RM( 35 ) = { 1, 15, KEY_4, 0 }; // (HID(USBCode)"KEY_4")
Guide_RM( 36 ) = { 1, 15, KEY_5, 0 }; // (HID(USBCode)"KEY_5")
Guide_RM( 37 ) = { 1, 15, KEY_6, 0 }; // (HID(USBCode)"KEY_6")
Guide_RM( 38 ) = { 1, 15, KEY_7, 0 }; // (HID(USBCode)"KEY_7")
Guide_RM( 39 ) = { 1, 15, KEY_8, 0 }; // (HID(USBCode)"KEY_8")
Guide_RM( 40 ) = { 1, 15, KEY_9, 0 }; // (HID(USBCode)"KEY_9")
Guide_RM( 41 ) = { 1, 15, KEY_0, 0 }; // (HID(USBCode)"KEY_0")
Guide_RM( 42 ) = { 1, 15, KEY_ENTER, 0 }; // (HID(USBCode)"KEY_ENTER")
Guide_RM( 43 ) = { 1, 15, KEY_ESC, 0 }; // (HID(USBCode)"KEY_ESC")
Guide_RM( 44 ) = { 1, 15, KEY_BACKSPACE, 0 }; // (HID(USBCode)"KEY_BACKSPACE")
Guide_RM( 45 ) = { 1, 15, KEY_TAB, 0 }; // (HID(USBCode)"KEY_TAB")
Guide_RM( 46 ) = { 1, 15, KEY_SPACE, 0 }; // (HID(USBCode)"KEY_SPACE")
Guide_RM( 47 ) = { 1, 15, KEY_MINUS, 0 }; // (HID(USBCode)"KEY_MINUS")
Guide_RM( 48 ) = { 1, 15, KEY_EQUAL, 0 }; // (HID(USBCode)"KEY_EQUAL")
Guide_RM( 49 ) = { 1, 15, KEY_LEFT_BRACKET, 0 }; // (HID(USBCode)"KEY_LEFT_BRACKET")
Guide_RM( 50 ) = { 1, 15, KEY_RIGHT_BRACKET, 0 }; // (HID(USBCode)"KEY_RIGHT_BRACKET")
Guide_RM( 51 ) = { 1, 15, KEY_BACKSLASH, 0 }; // (HID(USBCode)"KEY_BACKSLASH")
Guide_RM( 52 ) = { 1, 15, KEY_SEMICOLON, 0 }; // (HID(USBCode)"KEY_SEMICOLON")
Guide_RM( 53 ) = { 1, 15, KEY_QUOTE, 0 }; // (HID(USBCode)"KEY_QUOTE")
Guide_RM( 54 ) = { 1, 15, KEY_BACKTICK, 0 }; // (HID(USBCode)"KEY_BACKTICK")
Guide_RM( 55 ) = { 1, 15, KEY_COMMA, 0 }; // (HID(USBCode)"KEY_COMMA")
Guide_RM( 56 ) = { 1, 15, KEY_PERIOD, 0 }; // (HID(USBCode)"KEY_PERIOD")
Guide_RM( 57 ) = { 1, 15, KEY_SLASH, 0 }; // (HID(USBCode)"KEY_SLASH")
Guide_RM( 58 ) = { 1, 15, KEY_F1, 0 }; // (HID(USBCode)"KEY_F1")
Guide_RM( 59 ) = { 1, 15, KEY_F2, 0 }; // (HID(USBCode)"KEY_F2")
Guide_RM( 60 ) = { 1, 15, KEY_F3, 0 }; // (HID(USBCode)"KEY_F3")
Guide_RM( 61 ) = { 1, 15, KEY_F4, 0 }; // (HID(USBCode)"KEY_F4")
Guide_RM( 62 ) = { 1, 15, KEY_F5, 0 }; // (HID(USBCode)"KEY_F5")
Guide_RM( 63 ) = { 1, 15, KEY_F6, 0 }; // (HID(USBCode)"KEY_F6")
Guide_RM( 64 ) = { 1, 15, KEY_F7, 0 }; // (HID(USBCode)"KEY_F7")
Guide_RM( 65 ) = { 1, 15, KEY_F8, 0 }; // (HID(USBCode)"KEY_F8")
Guide_RM( 66 ) = { 1, 15, KEY_F9, 0 }; // (HID(USBCode)"KEY_F9")
Guide_RM( 67 ) = { 1, 15, KEY_F10, 0 }; // (HID(USBCode)"KEY_F10")
Guide_RM( 68 ) = { 1, 15, KEY_F11, 0 }; // (HID(USBCode)"KEY_F11")
Guide_RM( 69 ) = { 1, 15, KEY_F12, 0 }; // (HID(USBCode)"KEY_F12")
Guide_RM( 70 ) = { 1, 15, KEY_HOME, 0 }; // (HID(USBCode)"KEY_HOME")
Guide_RM( 71 ) = { 1, 15, KEY_PAGE_UP, 0 }; // (HID(USBCode)"KEY_PAGE_UP")
Guide_RM( 72 ) = { 1, 15, KEY_DELETE, 0 }; // (HID(USBCode)"KEY_DELETE")
Guide_RM( 73 ) = { 1, 15, KEY_END, 0 }; // (HID(USBCode)"KEY_END")
Guide_RM( 74 ) = { 1, 15, KEY_PAGE_DOWN, 0 }; // (HID(USBCode)"KEY_PAGE_DOWN")
Guide_RM( 75 ) = { 1, 15, KEY_RIGHT, 0 }; // (HID(USBCode)"KEY_RIGHT")
Guide_RM( 76 ) = { 1, 15, KEY_LEFT, 0 }; // (HID(USBCode)"KEY_LEFT")
Guide_RM( 77 ) = { 1, 15, KEY_DOWN, 0 }; // (HID(USBCode)"KEY_DOWN")
Guide_RM( 78 ) = { 1, 15, KEY_UP, 0 }; // (HID(USBCode)"KEY_UP")
Guide_RM( 79 ) = { 1, 15, KEY_ISO_SLASH, 0 }; // (HID(USBCode)"KEY_ISO_SLASH")
Guide_RM( 80 ) = { 1, 15, KEY_LCTRL, 0 }; // (HID(USBCode)"KEY_LCTRL")
Guide_RM( 81 ) = { 1, 15, KEY_LSHIFT, 0 }; // (HID(USBCode)"KEY_LSHIFT")
Guide_RM( 82 ) = { 2, 15, KEY_LSHIFT, 15, KEY_9, 0 }; // (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_9")
Guide_RM( 83 ) = { 2, 15, KEY_LSHIFT, 15, KEY_0, 0 }; // (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_0")
Guide_RM( 84 ) = { 2, 15, KEY_LSHIFT, 15, KEY_LEFT_BRACKET, 0 }; // (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_LEFT_BRACKET")
Guide_RM( 85 ) = { 2, 15, KEY_LSHIFT, 15, KEY_RIGHT_BRACKET, 0 }; // (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_RIGHT_BRACKET")
Guide_RM( 86 ) = { 1, 15, KEY_LALT, 0 }; // (HID(USBCode)"KEY_LALT")
Guide_RM( 87 ) = { 1, 15, KEY_LGUI, 0 }; // (HID(USBCode)"KEY_LGUI")
Guide_RM( 88 ) = { 1, 15, KEY_RCTRL, 0 }; // (HID(USBCode)"KEY_RCTRL")
Guide_RM( 89 ) = { 1, 15, KEY_RSHIFT, 0 }; // (HID(USBCode)"KEY_RSHIFT")
Guide_RM( 90 ) = { 1, 15, KEY_RGUI, 0 }; // (HID(USBCode)"KEY_RGUI")
Guide_RM( 91 ) = { 1, 9, 0 }; // (flashMode())
Guide_RM( 92 ) = { 2, 6, 1, 0, 1, 0 }; // (layerShift(1) + LCDLayerDisplay())
Guide_RM( 93 ) = { 2, 6, 2, 0, 1, 0 }; // (layerShift(2) + LCDLayerDisplay())
Guide_RM( 94 ) = { 2, 6, 3, 0, 1, 0 }; // (layerShift(3) + LCDLayerDisplay())
Guide_RM( 95 ) = { 2, 6, 7, 0, 1, 0 }; // (layerShift(7) + LCDLayerDisplay())
Guide_RM( 96 ) = { 1, 2, 3, 15, 0 }; // (ledControl(3,15))
Guide_RM( 97 ) = { 1, 2, 4, 15, 0 }; // (ledControl(4,15))
Guide_RM( 98 ) = { 1, 2, 5, 0, 0 }; // (ledControl(5,0))


// -- Result Macro List

// Indexed Table of Result Macros
const ResultMacro ResultMacroList[] = {
	Define_RM( 0 ), // (HID(ConsCode)"CONSUMER_SCAN_NEXT_TRACK")
	Define_RM( 1 ), // (HID(ConsCode)"CONSUMER_SCAN_PREVIOUS_TRACK")
	Define_RM( 2 ), // (HID(ConsCode)"CONSUMER_PAUSE_PLAY")
	Define_RM( 3 ), // (HID(ConsCode)"CONSUMER_MUTE")
	Define_RM( 4 ), // (HID(ConsCode)"CONSUMER_VOLUME_UP")
	Define_RM( 5 ), // (HID(ConsCode)"CONSUMER_VOLUME_DOWN")
	Define_RM( 6 ), // (HID(USBCode)"KEY_A")
	Define_RM( 7 ), // (HID(USBCode)"KEY_B")
	Define_RM( 8 ), // (HID(USBCode)"KEY_C")
	Define_RM( 9 ), // (HID(USBCode)"KEY_D")
	Define_RM( 10 ), // (HID(USBCode)"KEY_E")
	Define_RM( 11 ), // (HID(USBCode)"KEY_F")
	Define_RM( 12 ), // (HID(USBCode)"KEY_G")
	Define_RM( 13 ), // (HID(USBCode)"KEY_H")
	Define_RM( 14 ), // (HID(USBCode)"KEY_I")
	Define_RM( 15 ), // (HID(USBCode)"KEY_J")
	Define_RM( 16 ), // (HID(USBCode)"KEY_K")
	Define_RM( 17 ), // (HID(USBCode)"KEY_L")
	Define_RM( 18 ), // (HID(USBCode)"KEY_M")
	Define_RM( 19 ), // (HID(USBCode)"KEY_N")
	Define_RM( 20 ), // (HID(USBCode)"KEY_O")
	Define_RM( 21 ), // (HID(USBCode)"KEY_P")
	Define_RM( 22 ), // (HID(USBCode)"KEY_Q")
	Define_RM( 23 ), // (HID(USBCode)"KEY_R")
	Define_RM( 24 ), // (HID(USBCode)"KEY_S")
	Define_RM( 25 ), // (HID(USBCode)"KEY_T")
	Define_RM( 26 ), // (HID(USBCode)"KEY_U")
	Define_RM( 27 ), // (HID(USBCode)"KEY_V")
	Define_RM( 28 ), // (HID(USBCode)"KEY_W")
	Define_RM( 29 ), // (HID(USBCode)"KEY_X")
	Define_RM( 30 ), // (HID(USBCode)"KEY_Y")
	Define_RM( 31 ), // (HID(USBCode)"KEY_Z")
	Define_RM( 32 ), // (HID(USBCode)"KEY_1")
	Define_RM( 33 ), // (HID(USBCode)"KEY_2")
	Define_RM( 34 ), // (HID(USBCode)"KEY_3")
	Define_RM( 35 ), // (HID(USBCode)"KEY_4")
	Define_RM( 36 ), // (HID(USBCode)"KEY_5")
	Define_RM( 37 ), // (HID(USBCode)"KEY_6")
	Define_RM( 38 ), // (HID(USBCode)"KEY_7")
	Define_RM( 39 ), // (HID(USBCode)"KEY_8")
	Define_RM( 40 ), // (HID(USBCode)"KEY_9")
	Define_RM( 41 ), // (HID(USBCode)"KEY_0")
	Define_RM( 42 ), // (HID(USBCode)"KEY_ENTER")
	Define_RM( 43 ), // (HID(USBCode)"KEY_ESC")
	Define_RM( 44 ), // (HID(USBCode)"KEY_BACKSPACE")
	Define_RM( 45 ), // (HID(USBCode)"KEY_TAB")
	Define_RM( 46 ), // (HID(USBCode)"KEY_SPACE")
	Define_RM( 47 ), // (HID(USBCode)"KEY_MINUS")
	Define_RM( 48 ), // (HID(USBCode)"KEY_EQUAL")
	Define_RM( 49 ), // (HID(USBCode)"KEY_LEFT_BRACKET")
	Define_RM( 50 ), // (HID(USBCode)"KEY_RIGHT_BRACKET")
	Define_RM( 51 ), // (HID(USBCode)"KEY_BACKSLASH")
	Define_RM( 52 ), // (HID(USBCode)"KEY_SEMICOLON")
	Define_RM( 53 ), // (HID(USBCode)"KEY_QUOTE")
	Define_RM( 54 ), // (HID(USBCode)"KEY_BACKTICK")
	Define_RM( 55 ), // (HID(USBCode)"KEY_COMMA")
	Define_RM( 56 ), // (HID(USBCode)"KEY_PERIOD")
	Define_RM( 57 ), // (HID(USBCode)"KEY_SLASH")
	Define_RM( 58 ), // (HID(USBCode)"KEY_F1")
	Define_RM( 59 ), // (HID(USBCode)"KEY_F2")
	Define_RM( 60 ), // (HID(USBCode)"KEY_F3")
	Define_RM( 61 ), // (HID(USBCode)"KEY_F4")
	Define_RM( 62 ), // (HID(USBCode)"KEY_F5")
	Define_RM( 63 ), // (HID(USBCode)"KEY_F6")
	Define_RM( 64 ), // (HID(USBCode)"KEY_F7")
	Define_RM( 65 ), // (HID(USBCode)"KEY_F8")
	Define_RM( 66 ), // (HID(USBCode)"KEY_F9")
	Define_RM( 67 ), // (HID(USBCode)"KEY_F10")
	Define_RM( 68 ), // (HID(USBCode)"KEY_F11")
	Define_RM( 69 ), // (HID(USBCode)"KEY_F12")
	Define_RM( 70 ), // (HID(USBCode)"KEY_HOME")
	Define_RM( 71 ), // (HID(USBCode)"KEY_PAGE_UP")
	Define_RM( 72 ), // (HID(USBCode)"KEY_DELETE")
	Define_RM( 73 ), // (HID(USBCode)"KEY_END")
	Define_RM( 74 ), // (HID(USBCode)"KEY_PAGE_DOWN")
	Define_RM( 75 ), // (HID(USBCode)"KEY_RIGHT")
	Define_RM( 76 ), // (HID(USBCode)"KEY_LEFT")
	Define_RM( 77 ), // (HID(USBCode)"KEY_DOWN")
	Define_RM( 78 ), // (HID(USBCode)"KEY_UP")
	Define_RM( 79 ), // (HID(USBCode)"KEY_ISO_SLASH")
	Define_RM( 80 ), // (HID(USBCode)"KEY_LCTRL")
	Define_RM( 81 ), // (HID(USBCode)"KEY_LSHIFT")
	Define_RM( 82 ), // (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_9")
	Define_RM( 83 ), // (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_0")
	Define_RM( 84 ), // (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_LEFT_BRACKET")
	Define_RM( 85 ), // (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_RIGHT_BRACKET")
	Define_RM( 86 ), // (HID(USBCode)"KEY_LALT")
	Define_RM( 87 ), // (HID(USBCode)"KEY_LGUI")
	Define_RM( 88 ), // (HID(USBCode)"KEY_RCTRL")
	Define_RM( 89 ), // (HID(USBCode)"KEY_RSHIFT")
	Define_RM( 90 ), // (HID(USBCode)"KEY_RGUI")
	Define_RM( 91 ), // (flashMode())
	Define_RM( 92 ), // (layerShift(1) + LCDLayerDisplay())
	Define_RM( 93 ), // (layerShift(2) + LCDLayerDisplay())
	Define_RM( 94 ), // (layerShift(3) + LCDLayerDisplay())
	Define_RM( 95 ), // (layerShift(7) + LCDLayerDisplay())
	Define_RM( 96 ), // (ledControl(3,15))
	Define_RM( 97 ), // (ledControl(4,15))
	Define_RM( 98 ), // (ledControl(5,0))
};


// -- Trigger Macro Record

// Keeps a record/state of each result macro
ResultMacroRecord ResultMacroRecordList[ ResultMacroNum ];


// -- Trigger Macros

// Trigger Macro Guides
Guide_TM( 0 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x03, 0 }; // (S003)
Guide_TM( 1 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x04, 0 }; // (S004)
Guide_TM( 2 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x05, 0 }; // (S005)
Guide_TM( 3 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x06, 0 }; // (S006)
Guide_TM( 4 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x07, 0 }; // (S007)
Guide_TM( 5 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x08, 0 }; // (S008)
Guide_TM( 6 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x09, 0 }; // (S009)
Guide_TM( 7 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0C, 0 }; // (S012)
Guide_TM( 8 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0D, 0 }; // (S013)
Guide_TM( 9 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0E, 0 }; // (S014)
Guide_TM( 10 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x0F, 0 }; // (S015)
Guide_TM( 11 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x10, 0 }; // (S016)
Guide_TM( 12 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x11, 0 }; // (S017)
Guide_TM( 13 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x12, 0 }; // (S018)
Guide_TM( 14 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x16, 0 }; // (S022)
Guide_TM( 15 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x17, 0 }; // (S023)
Guide_TM( 16 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x18, 0 }; // (S024)
Guide_TM( 17 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x19, 0 }; // (S025)
Guide_TM( 18 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1A, 0 }; // (S026)
Guide_TM( 19 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1B, 0 }; // (S027)
Guide_TM( 20 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1C, 0 }; // (S028)
Guide_TM( 21 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1D, 0 }; // (S029)
Guide_TM( 22 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1E, 0 }; // (S030)
Guide_TM( 23 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x1F, 0 }; // (S031)
Guide_TM( 24 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x20, 0 }; // (S032)
Guide_TM( 25 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x21, 0 }; // (S033)
Guide_TM( 26 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x22, 0 }; // (S034)
Guide_TM( 27 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x23, 0 }; // (S035)
Guide_TM( 28 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x24, 0 }; // (S036)
Guide_TM( 29 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x25, 0 }; // (S037)
Guide_TM( 30 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x26, 0 }; // (S038)
Guide_TM( 31 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x27, 0 }; // (S039)
Guide_TM( 32 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x28, 0 }; // (S040)
Guide_TM( 33 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x29, 0 }; // (S041)
Guide_TM( 34 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2A, 0 }; // (S042)
Guide_TM( 35 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2B, 0 }; // (S043)
Guide_TM( 36 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2C, 0 }; // (S044)
Guide_TM( 37 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x2D, 0 }; // (S045)
Guide_TM( 38 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x30, 0 }; // (S048)
Guide_TM( 39 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x31, 0 }; // (S049)
Guide_TM( 40 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x32, 0 }; // (S050)
Guide_TM( 41 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x33, 0 }; // (S051)
Guide_TM( 42 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x34, 0 }; // (S052)
Guide_TM( 43 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x35, 0 }; // (S053)
Guide_TM( 44 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x36, 0 }; // (S054)
Guide_TM( 45 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x39, 0 }; // (S057)
Guide_TM( 46 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3A, 0 }; // (S058)
Guide_TM( 47 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3B, 0 }; // (S059)
Guide_TM( 48 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3C, 0 }; // (S060)
Guide_TM( 49 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3D, 0 }; // (S061)
Guide_TM( 50 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3E, 0 }; // (S062)
Guide_TM( 51 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x3F, 0 }; // (S063)
Guide_TM( 52 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x43, 0 }; // (S067)
Guide_TM( 53 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x44, 0 }; // (S068)
Guide_TM( 54 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x45, 0 }; // (S069)
Guide_TM( 55 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x46, 0 }; // (S070)
Guide_TM( 56 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x47, 0 }; // (S071)
Guide_TM( 57 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x48, 0 }; // (S072)
Guide_TM( 58 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x49, 0 }; // (S073)
Guide_TM( 59 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x4A, 0 }; // (S074)
Guide_TM( 60 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x4B, 0 }; // (S075)
Guide_TM( 61 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x4C, 0 }; // (S076)
Guide_TM( 62 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x4D, 0 }; // (S077)
Guide_TM( 63 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x4E, 0 }; // (S078)
Guide_TM( 64 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x4F, 0 }; // (S079)
Guide_TM( 65 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x50, 0 }; // (S080)
Guide_TM( 66 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x51, 0 }; // (S081)
Guide_TM( 67 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x52, 0 }; // (S082)
Guide_TM( 68 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x53, 0 }; // (S083)
Guide_TM( 69 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x54, 0 }; // (S084)
Guide_TM( 70 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x55, 0 }; // (S085)
Guide_TM( 71 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x56, 0 }; // (S086)
Guide_TM( 72 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x57, 0 }; // (S087)
Guide_TM( 73 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x58, 0 }; // (S088)
Guide_TM( 74 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x59, 0 }; // (S089)
Guide_TM( 75 ) = { 1, TriggerType_Switch1, ScheduleType_P, 0x5A, 0 }; // (S090)


// -- Trigger Macro List

// Indexed Table of Trigger Macros
const TriggerMacro TriggerMacroList[] = {
	/* 0 */ Define_TM( 0, 49 ), // (S003) : (HID(USBCode)"KEY_LEFT_BRACKET");
	/* 1 */ Define_TM( 0, 68 ), // (S003) : (HID(USBCode)"KEY_F11");
	/* 2 */ Define_TM( 1, 36 ), // (S004) : (HID(USBCode)"KEY_5");
	/* 3 */ Define_TM( 1, 62 ), // (S004) : (HID(USBCode)"KEY_F5");
	/* 4 */ Define_TM( 2, 35 ), // (S005) : (HID(USBCode)"KEY_4");
	/* 5 */ Define_TM( 2, 61 ), // (S005) : (HID(USBCode)"KEY_F4");
	/* 6 */ Define_TM( 3, 34 ), // (S006) : (HID(USBCode)"KEY_3");
	/* 7 */ Define_TM( 3, 60 ), // (S006) : (HID(USBCode)"KEY_F3");
	/* 8 */ Define_TM( 4, 33 ), // (S007) : (HID(USBCode)"KEY_2");
	/* 9 */ Define_TM( 4, 59 ), // (S007) : (HID(USBCode)"KEY_F2");
	/* 10 */ Define_TM( 5, 32 ), // (S008) : (HID(USBCode)"KEY_1");
	/* 11 */ Define_TM( 5, 58 ), // (S008) : (HID(USBCode)"KEY_F1");
	/* 12 */ Define_TM( 6, 43 ), // (S009) : (HID(USBCode)"KEY_ESC");
	/* 13 */ Define_TM( 6, 91 ), // (S009) : (flashMode());
	/* 14 */ Define_TM( 7, 82 ), // (S012) : (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_9");
	/* 15 */ Define_TM( 7, 92 ), // (S012) : (layerShift(1) + LCDLayerDisplay());
	/* 16 */ Define_TM( 8, 25 ), // (S013) : (HID(USBCode)"KEY_T");
	/* 17 */ Define_TM( 9, 23 ), // (S014) : (HID(USBCode)"KEY_R");
	/* 18 */ Define_TM( 10, 10 ), // (S015) : (HID(USBCode)"KEY_E");
	/* 19 */ Define_TM( 11, 28 ), // (S016) : (HID(USBCode)"KEY_W");
	/* 20 */ Define_TM( 12, 22 ), // (S017) : (HID(USBCode)"KEY_Q");
	/* 21 */ Define_TM( 13, 87 ), // (S018) : (HID(USBCode)"KEY_LGUI");
	/* 22 */ Define_TM( 14, 12 ), // (S022) : (HID(USBCode)"KEY_G");
	/* 23 */ Define_TM( 15, 11 ), // (S023) : (HID(USBCode)"KEY_F");
	/* 24 */ Define_TM( 16, 9 ), // (S024) : (HID(USBCode)"KEY_D");
	/* 25 */ Define_TM( 17, 24 ), // (S025) : (HID(USBCode)"KEY_S");
	/* 26 */ Define_TM( 18, 6 ), // (S026) : (HID(USBCode)"KEY_A");
	/* 27 */ Define_TM( 19, 80 ), // (S027) : (HID(USBCode)"KEY_LCTRL");
	/* 28 */ Define_TM( 20, 4 ), // (S028) : (HID(ConsCode)"CONSUMER_VOLUME_UP");
	/* 29 */ Define_TM( 20, 97 ), // (S028) : (ledControl(4,15));
	/* 30 */ Define_TM( 21, 5 ), // (S029) : (HID(ConsCode)"CONSUMER_VOLUME_DOWN");
	/* 31 */ Define_TM( 21, 96 ), // (S029) : (ledControl(3,15));
	/* 32 */ Define_TM( 22, 84 ), // (S030) : (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_LEFT_BRACKET");
	/* 33 */ Define_TM( 22, 93 ), // (S030) : (layerShift(2) + LCDLayerDisplay());
	/* 34 */ Define_TM( 23, 7 ), // (S031) : (HID(USBCode)"KEY_B");
	/* 35 */ Define_TM( 24, 27 ), // (S032) : (HID(USBCode)"KEY_V");
	/* 36 */ Define_TM( 25, 8 ), // (S033) : (HID(USBCode)"KEY_C");
	/* 37 */ Define_TM( 26, 29 ), // (S034) : (HID(USBCode)"KEY_X");
	/* 38 */ Define_TM( 27, 31 ), // (S035) : (HID(USBCode)"KEY_Z");
	/* 39 */ Define_TM( 28, 81 ), // (S036) : (HID(USBCode)"KEY_LSHIFT");
	/* 40 */ Define_TM( 29, 71 ), // (S037) : (HID(USBCode)"KEY_PAGE_UP");
	/* 41 */ Define_TM( 30, 74 ), // (S038) : (HID(USBCode)"KEY_PAGE_DOWN");
	/* 42 */ Define_TM( 31, 86 ), // (S039) : (HID(USBCode)"KEY_LALT");
	/* 43 */ Define_TM( 32, 44 ), // (S040) : (HID(USBCode)"KEY_BACKSPACE");
	/* 44 */ Define_TM( 33, 48 ), // (S041) : (HID(USBCode)"KEY_EQUAL");
	/* 45 */ Define_TM( 33, 0 ), // (S041) : (HID(ConsCode)"CONSUMER_SCAN_NEXT_TRACK");
	/* 46 */ Define_TM( 34, 47 ), // (S042) : (HID(USBCode)"KEY_MINUS");
	/* 47 */ Define_TM( 34, 1 ), // (S042) : (HID(ConsCode)"CONSUMER_SCAN_PREVIOUS_TRACK");
	/* 48 */ Define_TM( 35, 72 ), // (S043) : (HID(USBCode)"KEY_DELETE");
	/* 49 */ Define_TM( 35, 94 ), // (S043) : (layerShift(3) + LCDLayerDisplay());
	/* 50 */ Define_TM( 36, 45 ), // (S044) : (HID(USBCode)"KEY_TAB");
	/* 51 */ Define_TM( 37, 92 ), // (S045) : (layerShift(1) + LCDLayerDisplay());
	/* 52 */ Define_TM( 38, 50 ), // (S048) : (HID(USBCode)"KEY_RIGHT_BRACKET");
	/* 53 */ Define_TM( 38, 69 ), // (S048) : (HID(USBCode)"KEY_F12");
	/* 54 */ Define_TM( 39, 37 ), // (S049) : (HID(USBCode)"KEY_6");
	/* 55 */ Define_TM( 39, 63 ), // (S049) : (HID(USBCode)"KEY_F6");
	/* 56 */ Define_TM( 40, 38 ), // (S050) : (HID(USBCode)"KEY_7");
	/* 57 */ Define_TM( 40, 64 ), // (S050) : (HID(USBCode)"KEY_F7");
	/* 58 */ Define_TM( 41, 39 ), // (S051) : (HID(USBCode)"KEY_8");
	/* 59 */ Define_TM( 41, 65 ), // (S051) : (HID(USBCode)"KEY_F8");
	/* 60 */ Define_TM( 42, 40 ), // (S052) : (HID(USBCode)"KEY_9");
	/* 61 */ Define_TM( 42, 66 ), // (S052) : (HID(USBCode)"KEY_F9");
	/* 62 */ Define_TM( 43, 41 ), // (S053) : (HID(USBCode)"KEY_0");
	/* 63 */ Define_TM( 43, 67 ), // (S053) : (HID(USBCode)"KEY_F10");
	/* 64 */ Define_TM( 44, 43 ), // (S054) : (HID(USBCode)"KEY_ESC");
	/* 65 */ Define_TM( 44, 91 ), // (S054) : (flashMode());
	/* 66 */ Define_TM( 45, 83 ), // (S057) : (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_0");
	/* 67 */ Define_TM( 46, 30 ), // (S058) : (HID(USBCode)"KEY_Y");
	/* 68 */ Define_TM( 47, 26 ), // (S059) : (HID(USBCode)"KEY_U");
	/* 69 */ Define_TM( 48, 14 ), // (S060) : (HID(USBCode)"KEY_I");
	/* 70 */ Define_TM( 49, 20 ), // (S061) : (HID(USBCode)"KEY_O");
	/* 71 */ Define_TM( 50, 21 ), // (S062) : (HID(USBCode)"KEY_P");
	/* 72 */ Define_TM( 51, 90 ), // (S063) : (HID(USBCode)"KEY_RGUI");
	/* 73 */ Define_TM( 52, 13 ), // (S067) : (HID(USBCode)"KEY_H");
	/* 74 */ Define_TM( 52, 76 ), // (S067) : (HID(USBCode)"KEY_LEFT");
	/* 75 */ Define_TM( 53, 15 ), // (S068) : (HID(USBCode)"KEY_J");
	/* 76 */ Define_TM( 53, 77 ), // (S068) : (HID(USBCode)"KEY_DOWN");
	/* 77 */ Define_TM( 54, 16 ), // (S069) : (HID(USBCode)"KEY_K");
	/* 78 */ Define_TM( 54, 78 ), // (S069) : (HID(USBCode)"KEY_UP");
	/* 79 */ Define_TM( 55, 17 ), // (S070) : (HID(USBCode)"KEY_L");
	/* 80 */ Define_TM( 55, 75 ), // (S070) : (HID(USBCode)"KEY_RIGHT");
	/* 81 */ Define_TM( 56, 52 ), // (S071) : (HID(USBCode)"KEY_SEMICOLON");
	/* 82 */ Define_TM( 57, 88 ), // (S072) : (HID(USBCode)"KEY_RCTRL");
	/* 83 */ Define_TM( 58, 3 ), // (S073) : (HID(ConsCode)"CONSUMER_MUTE");
	/* 84 */ Define_TM( 58, 98 ), // (S073) : (ledControl(5,0));
	/* 85 */ Define_TM( 59, 2 ), // (S074) : (HID(ConsCode)"CONSUMER_PAUSE_PLAY");
	/* 86 */ Define_TM( 60, 85 ), // (S075) : (HID(USBCode)"KEY_LSHIFT" + HID(USBCode)"KEY_RIGHT_BRACKET");
	/* 87 */ Define_TM( 60, 95 ), // (S075) : (layerShift(7) + LCDLayerDisplay());
	/* 88 */ Define_TM( 61, 19 ), // (S076) : (HID(USBCode)"KEY_N");
	/* 89 */ Define_TM( 62, 18 ), // (S077) : (HID(USBCode)"KEY_M");
	/* 90 */ Define_TM( 63, 55 ), // (S078) : (HID(USBCode)"KEY_COMMA");
	/* 91 */ Define_TM( 64, 56 ), // (S079) : (HID(USBCode)"KEY_PERIOD");
	/* 92 */ Define_TM( 65, 57 ), // (S080) : (HID(USBCode)"KEY_SLASH");
	/* 93 */ Define_TM( 66, 89 ), // (S081) : (HID(USBCode)"KEY_RSHIFT");
	/* 94 */ Define_TM( 67, 70 ), // (S082) : (HID(USBCode)"KEY_HOME");
	/* 95 */ Define_TM( 68, 73 ), // (S083) : (HID(USBCode)"KEY_END");
	/* 96 */ Define_TM( 69, 42 ), // (S084) : (HID(USBCode)"KEY_ENTER");
	/* 97 */ Define_TM( 70, 46 ), // (S085) : (HID(USBCode)"KEY_SPACE");
	/* 98 */ Define_TM( 71, 54 ), // (S086) : (HID(USBCode)"KEY_BACKTICK");
	/* 99 */ Define_TM( 72, 53 ), // (S087) : (HID(USBCode)"KEY_QUOTE");
	/* 100 */ Define_TM( 73, 51 ), // (S088) : (HID(USBCode)"KEY_BACKSLASH");
	/* 101 */ Define_TM( 74, 79 ), // (S089) : (HID(USBCode)"KEY_ISO_SLASH");
	/* 102 */ Define_TM( 75, 92 ), // (S090) : (layerShift(1) + LCDLayerDisplay());
};


// -- Trigger Macro Record List

// Keeps a record/state of each trigger macro
TriggerMacroRecord TriggerMacroRecordList[ TriggerMacroNum ];



// ----- Trigger Maps -----

// MaxScanCode
// - This is retrieved from the KLL configuration
// - Should be corollated with the max scan code in the scan module
// - Maximum value is 0x100 (0x0 to 0xFF)
// - Increasing it beyond the keyboard's capabilities is just a waste of ram...
#define MaxScanCode 0x5A

// -- Trigger Lists
//
// Index 0: # of triggers in list
// Index n: pointer to trigger macro - use tm() macro

// - Default Layer -
Define_TL( default, 0x00 ) = { 0 };
Define_TL( default, 0x01 ) = { 0 };
Define_TL( default, 0x02 ) = { 0 };
Define_TL( default, 0x03 ) = { 1, 0 };
Define_TL( default, 0x04 ) = { 1, 2 };
Define_TL( default, 0x05 ) = { 1, 4 };
Define_TL( default, 0x06 ) = { 1, 6 };
Define_TL( default, 0x07 ) = { 1, 8 };
Define_TL( default, 0x08 ) = { 1, 10 };
Define_TL( default, 0x09 ) = { 1, 12 };
Define_TL( default, 0x0A ) = { 0 };
Define_TL( default, 0x0B ) = { 0 };
Define_TL( default, 0x0C ) = { 1, 14 };
Define_TL( default, 0x0D ) = { 1, 16 };
Define_TL( default, 0x0E ) = { 1, 17 };
Define_TL( default, 0x0F ) = { 1, 18 };
Define_TL( default, 0x10 ) = { 1, 19 };
Define_TL( default, 0x11 ) = { 1, 20 };
Define_TL( default, 0x12 ) = { 1, 21 };
Define_TL( default, 0x13 ) = { 0 };
Define_TL( default, 0x14 ) = { 0 };
Define_TL( default, 0x15 ) = { 0 };
Define_TL( default, 0x16 ) = { 1, 22 };
Define_TL( default, 0x17 ) = { 1, 23 };
Define_TL( default, 0x18 ) = { 1, 24 };
Define_TL( default, 0x19 ) = { 1, 25 };
Define_TL( default, 0x1A ) = { 1, 26 };
Define_TL( default, 0x1B ) = { 1, 27 };
Define_TL( default, 0x1C ) = { 1, 28 };
Define_TL( default, 0x1D ) = { 1, 30 };
Define_TL( default, 0x1E ) = { 1, 32 };
Define_TL( default, 0x1F ) = { 1, 34 };
Define_TL( default, 0x20 ) = { 1, 35 };
Define_TL( default, 0x21 ) = { 1, 36 };
Define_TL( default, 0x22 ) = { 1, 37 };
Define_TL( default, 0x23 ) = { 1, 38 };
Define_TL( default, 0x24 ) = { 1, 39 };
Define_TL( default, 0x25 ) = { 1, 40 };
Define_TL( default, 0x26 ) = { 1, 41 };
Define_TL( default, 0x27 ) = { 1, 42 };
Define_TL( default, 0x28 ) = { 1, 43 };
Define_TL( default, 0x29 ) = { 1, 44 };
Define_TL( default, 0x2A ) = { 1, 46 };
Define_TL( default, 0x2B ) = { 1, 48 };
Define_TL( default, 0x2C ) = { 1, 50 };
Define_TL( default, 0x2D ) = { 1, 51 };
Define_TL( default, 0x2E ) = { 0 };
Define_TL( default, 0x2F ) = { 0 };
Define_TL( default, 0x30 ) = { 1, 52 };
Define_TL( default, 0x31 ) = { 1, 54 };
Define_TL( default, 0x32 ) = { 1, 56 };
Define_TL( default, 0x33 ) = { 1, 58 };
Define_TL( default, 0x34 ) = { 1, 60 };
Define_TL( default, 0x35 ) = { 1, 62 };
Define_TL( default, 0x36 ) = { 1, 64 };
Define_TL( default, 0x37 ) = { 0 };
Define_TL( default, 0x38 ) = { 0 };
Define_TL( default, 0x39 ) = { 1, 66 };
Define_TL( default, 0x3A ) = { 1, 67 };
Define_TL( default, 0x3B ) = { 1, 68 };
Define_TL( default, 0x3C ) = { 1, 69 };
Define_TL( default, 0x3D ) = { 1, 70 };
Define_TL( default, 0x3E ) = { 1, 71 };
Define_TL( default, 0x3F ) = { 1, 72 };
Define_TL( default, 0x40 ) = { 0 };
Define_TL( default, 0x41 ) = { 0 };
Define_TL( default, 0x42 ) = { 0 };
Define_TL( default, 0x43 ) = { 1, 73 };
Define_TL( default, 0x44 ) = { 1, 75 };
Define_TL( default, 0x45 ) = { 1, 77 };
Define_TL( default, 0x46 ) = { 1, 79 };
Define_TL( default, 0x47 ) = { 1, 81 };
Define_TL( default, 0x48 ) = { 1, 82 };
Define_TL( default, 0x49 ) = { 1, 83 };
Define_TL( default, 0x4A ) = { 1, 85 };
Define_TL( default, 0x4B ) = { 1, 86 };
Define_TL( default, 0x4C ) = { 1, 88 };
Define_TL( default, 0x4D ) = { 1, 89 };
Define_TL( default, 0x4E ) = { 1, 90 };
Define_TL( default, 0x4F ) = { 1, 91 };
Define_TL( default, 0x50 ) = { 1, 92 };
Define_TL( default, 0x51 ) = { 1, 93 };
Define_TL( default, 0x52 ) = { 1, 94 };
Define_TL( default, 0x53 ) = { 1, 95 };
Define_TL( default, 0x54 ) = { 1, 96 };
Define_TL( default, 0x55 ) = { 1, 97 };
Define_TL( default, 0x56 ) = { 1, 98 };
Define_TL( default, 0x57 ) = { 1, 99 };
Define_TL( default, 0x58 ) = { 1, 100 };
Define_TL( default, 0x59 ) = { 1, 101 };
Define_TL( default, 0x5A ) = { 1, 102 };


// - Partial Layers -
// Partial Layer 1
Define_TL( layer1, 0x00 ) = { 1, 1 };
Define_TL( layer1, 0x01 ) = { 1, 3 };
Define_TL( layer1, 0x02 ) = { 1, 5 };
Define_TL( layer1, 0x03 ) = { 1, 7 };
Define_TL( layer1, 0x04 ) = { 1, 9 };
Define_TL( layer1, 0x05 ) = { 1, 11 };
Define_TL( layer1, 0x06 ) = { 1, 13 };
Define_TL( layer1, 0x07 ) = { 0 };
Define_TL( layer1, 0x08 ) = { 0 };
Define_TL( layer1, 0x09 ) = { 1, 15 };
Define_TL( layer1, 0x0A ) = { 0 };
Define_TL( layer1, 0x0B ) = { 0 };
Define_TL( layer1, 0x0C ) = { 0 };
Define_TL( layer1, 0x0D ) = { 0 };
Define_TL( layer1, 0x0E ) = { 0 };
Define_TL( layer1, 0x0F ) = { 0 };
Define_TL( layer1, 0x10 ) = { 0 };
Define_TL( layer1, 0x11 ) = { 0 };
Define_TL( layer1, 0x12 ) = { 0 };
Define_TL( layer1, 0x13 ) = { 0 };
Define_TL( layer1, 0x14 ) = { 0 };
Define_TL( layer1, 0x15 ) = { 0 };
Define_TL( layer1, 0x16 ) = { 0 };
Define_TL( layer1, 0x17 ) = { 0 };
Define_TL( layer1, 0x18 ) = { 0 };
Define_TL( layer1, 0x19 ) = { 1, 29 };
Define_TL( layer1, 0x1A ) = { 1, 31 };
Define_TL( layer1, 0x1B ) = { 1, 33 };
Define_TL( layer1, 0x1C ) = { 0 };
Define_TL( layer1, 0x1D ) = { 0 };
Define_TL( layer1, 0x1E ) = { 0 };
Define_TL( layer1, 0x1F ) = { 0 };
Define_TL( layer1, 0x20 ) = { 0 };
Define_TL( layer1, 0x21 ) = { 0 };
Define_TL( layer1, 0x22 ) = { 0 };
Define_TL( layer1, 0x23 ) = { 0 };
Define_TL( layer1, 0x24 ) = { 0 };
Define_TL( layer1, 0x25 ) = { 0 };
Define_TL( layer1, 0x26 ) = { 1, 45 };
Define_TL( layer1, 0x27 ) = { 1, 47 };
Define_TL( layer1, 0x28 ) = { 1, 49 };
Define_TL( layer1, 0x29 ) = { 0 };
Define_TL( layer1, 0x2A ) = { 0 };
Define_TL( layer1, 0x2B ) = { 0 };
Define_TL( layer1, 0x2C ) = { 0 };
Define_TL( layer1, 0x2D ) = { 1, 53 };
Define_TL( layer1, 0x2E ) = { 1, 55 };
Define_TL( layer1, 0x2F ) = { 1, 57 };
Define_TL( layer1, 0x30 ) = { 1, 59 };
Define_TL( layer1, 0x31 ) = { 1, 61 };
Define_TL( layer1, 0x32 ) = { 1, 63 };
Define_TL( layer1, 0x33 ) = { 1, 65 };
Define_TL( layer1, 0x34 ) = { 0 };
Define_TL( layer1, 0x35 ) = { 0 };
Define_TL( layer1, 0x36 ) = { 0 };
Define_TL( layer1, 0x37 ) = { 0 };
Define_TL( layer1, 0x38 ) = { 0 };
Define_TL( layer1, 0x39 ) = { 0 };
Define_TL( layer1, 0x3A ) = { 0 };
Define_TL( layer1, 0x3B ) = { 0 };
Define_TL( layer1, 0x3C ) = { 0 };
Define_TL( layer1, 0x3D ) = { 0 };
Define_TL( layer1, 0x3E ) = { 0 };
Define_TL( layer1, 0x3F ) = { 0 };
Define_TL( layer1, 0x40 ) = { 1, 74 };
Define_TL( layer1, 0x41 ) = { 1, 76 };
Define_TL( layer1, 0x42 ) = { 1, 78 };
Define_TL( layer1, 0x43 ) = { 1, 80 };
Define_TL( layer1, 0x44 ) = { 0 };
Define_TL( layer1, 0x45 ) = { 0 };
Define_TL( layer1, 0x46 ) = { 1, 84 };
Define_TL( layer1, 0x47 ) = { 0 };
Define_TL( layer1, 0x48 ) = { 1, 87 };


// -- ScanCode Offset Map
// Maps interconnect ids to scancode offsets
//
// Only used for keyboards with an interconnect
const uint8_t InterconnectOffsetList[] = {
	0x00,
	0x2D,
	0x5A,
};


// -- ScanCode Indexed Maps
// Maps to a trigger list of macro pointers
//                 _
// <scan code> -> |T|
//                |r| -> <trigger macro pointer 1>
//                |i|
//                |g| -> <trigger macro pointer 2>
//                |g|
//                |e| -> <trigger macro pointer 3>
//                |r|
//                |s| -> <trigger macro pointer n>
//                 -

// - Default Map for ScanCode Lookup -
const nat_ptr_t *default_scanMap[] = { 
default_tl_0x00, default_tl_0x01, default_tl_0x02, default_tl_0x03, default_tl_0x04, default_tl_0x05, default_tl_0x06, default_tl_0x07, default_tl_0x08, default_tl_0x09, default_tl_0x0A, default_tl_0x0B, default_tl_0x0C, default_tl_0x0D, default_tl_0x0E, default_tl_0x0F, default_tl_0x10, default_tl_0x11, default_tl_0x12, default_tl_0x13, default_tl_0x14, default_tl_0x15, default_tl_0x16, default_tl_0x17, default_tl_0x18, default_tl_0x19, default_tl_0x1A, default_tl_0x1B, default_tl_0x1C, default_tl_0x1D, default_tl_0x1E, default_tl_0x1F, default_tl_0x20, default_tl_0x21, default_tl_0x22, default_tl_0x23, default_tl_0x24, default_tl_0x25, default_tl_0x26, default_tl_0x27, default_tl_0x28, default_tl_0x29, default_tl_0x2A, default_tl_0x2B, default_tl_0x2C, default_tl_0x2D, default_tl_0x2E, default_tl_0x2F, default_tl_0x30, default_tl_0x31, default_tl_0x32, default_tl_0x33, default_tl_0x34, default_tl_0x35, default_tl_0x36, default_tl_0x37, default_tl_0x38, default_tl_0x39, default_tl_0x3A, default_tl_0x3B, default_tl_0x3C, default_tl_0x3D, default_tl_0x3E, default_tl_0x3F, default_tl_0x40, default_tl_0x41, default_tl_0x42, default_tl_0x43, default_tl_0x44, default_tl_0x45, default_tl_0x46, default_tl_0x47, default_tl_0x48, default_tl_0x49, default_tl_0x4A, default_tl_0x4B, default_tl_0x4C, default_tl_0x4D, default_tl_0x4E, default_tl_0x4F, default_tl_0x50, default_tl_0x51, default_tl_0x52, default_tl_0x53, default_tl_0x54, default_tl_0x55, default_tl_0x56, default_tl_0x57, default_tl_0x58, default_tl_0x59, default_tl_0x5A
};


// - Partial Layer ScanCode Lookup Maps -
// Partial Layer 1
const nat_ptr_t *layer1_scanMap[] = { 
layer1_tl_0x00, layer1_tl_0x01, layer1_tl_0x02, layer1_tl_0x03, layer1_tl_0x04, layer1_tl_0x05, layer1_tl_0x06, layer1_tl_0x07, layer1_tl_0x08, layer1_tl_0x09, layer1_tl_0x0A, layer1_tl_0x0B, layer1_tl_0x0C, layer1_tl_0x0D, layer1_tl_0x0E, layer1_tl_0x0F, layer1_tl_0x10, layer1_tl_0x11, layer1_tl_0x12, layer1_tl_0x13, layer1_tl_0x14, layer1_tl_0x15, layer1_tl_0x16, layer1_tl_0x17, layer1_tl_0x18, layer1_tl_0x19, layer1_tl_0x1A, layer1_tl_0x1B, layer1_tl_0x1C, layer1_tl_0x1D, layer1_tl_0x1E, layer1_tl_0x1F, layer1_tl_0x20, layer1_tl_0x21, layer1_tl_0x22, layer1_tl_0x23, layer1_tl_0x24, layer1_tl_0x25, layer1_tl_0x26, layer1_tl_0x27, layer1_tl_0x28, layer1_tl_0x29, layer1_tl_0x2A, layer1_tl_0x2B, layer1_tl_0x2C, layer1_tl_0x2D, layer1_tl_0x2E, layer1_tl_0x2F, layer1_tl_0x30, layer1_tl_0x31, layer1_tl_0x32, layer1_tl_0x33, layer1_tl_0x34, layer1_tl_0x35, layer1_tl_0x36, layer1_tl_0x37, layer1_tl_0x38, layer1_tl_0x39, layer1_tl_0x3A, layer1_tl_0x3B, layer1_tl_0x3C, layer1_tl_0x3D, layer1_tl_0x3E, layer1_tl_0x3F, layer1_tl_0x40, layer1_tl_0x41, layer1_tl_0x42, layer1_tl_0x43, layer1_tl_0x44, layer1_tl_0x45, layer1_tl_0x46, layer1_tl_0x47, layer1_tl_0x48
};



// ----- Layer Index -----

// -- Layer Index List
//
// Index 0: Default map
// Index n: Additional layers
const Layer LayerIndex[] = {
	Layer_IN( default_scanMap, "D: _home_oliver_repos_ergodox_Scan_Devices_ISSILed@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Scan_Devices_STLcd@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Scan_Devices_UARTConnect@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Macro_PartialMap@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Macro_PixelMap@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Output_HID-IO@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Output_USB@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Debug_latency@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['scancode_map']_processed.kll + _home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['leftHand']_processed.kll + _home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['slave1']_processed.kll + _home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['rightHand']_processed.kll + @['layer-default']_processed.kll + _home_oliver_repos_ergodox_kll_layouts_infinity_ergodox@['lcdFuncMap']_processed.kll", 0x00 ),
	Layer_IN( layer1_scanMap, "1: _home_oliver_repos_ergodox_Scan_Devices_ISSILed@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Scan_Devices_MatrixARMPeriodic@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Scan_Devices_STLcd@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Scan_Devices_UARTConnect@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Macro_PartialMap@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Macro_PixelMap@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Output_HID-IO@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Output_USB@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Debug_latency@['capabilities']_processed.kll + _home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['scancode_map']_processed.kll + _home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['leftHand']_processed.kll + _home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['slave1']_processed.kll + _home_oliver_repos_ergodox_Scan_Infinity_Ergodox@['rightHand']_processed.kll + @['layer-1']_processed.kll + _home_oliver_repos_ergodox_kll_layouts_infinity_ergodox@['lcdFuncMap']_processed.kll", 0x03 ),
};


// - Layer State
LayerStateType LayerState[ LayerNum ];



// ----- Key Positions -----

// -- Physical Key Positions
//
// Index 0: Key 1
// Each key has 6 dimensions
// x,y,z and rx,ry,rz (rotation)
// Units are in mm
const Position Key_Positions[] = {
	PositionEntry( 118.65, 1.0, 0.0, 0.0, 0.0, 0.0 ), // S003 <= x:118.65,y:1;
	PositionEntry( 99.6, 1.0, 0.0, 0.0, 0.0, 0.0 ), // S004 <= x:99.6,y:1;
	PositionEntry( 80.55, 2.0, 0.0, 0.0, 0.0, 0.0 ), // S005 <= x:80.55,y:2;
	PositionEntry( 61.5, 4.0, 0.0, 0.0, 0.0, 0.0 ), // S006 <= x:61.5,y:4;
	PositionEntry( 42.45, 3.0, 0.0, 0.0, 0.0, 0.0 ), // S007 <= x:42.45,y:3;
	PositionEntry( 23.4, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S008 <= x:23.4,y:0;
	PositionEntry( 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ), // S009 <= x:0,y:0;
	PositionEntry( 118.65, -23.05, 0.0, 0.0, 0.0, 0.0 ), // S012 <= x:118.65,y:-23.05;
	PositionEntry( 99.6, -18.05, 0.0, 0.0, 0.0, 0.0 ), // S013 <= x:99.6,y:-18.05;
	PositionEntry( 80.55, -17.05, 0.0, 0.0, 0.0, 0.0 ), // S014 <= x:80.55,y:-17.05;
	PositionEntry( 61.5, -15.05, 0.0, 0.0, 0.0, 0.0 ), // S015 <= x:61.5,y:-15.05;
	PositionEntry( 42.45, -16.05, 0.0, 0.0, 0.0, 0.0 ), // S016 <= x:42.45,y:-16.05;
	PositionEntry( 23.4, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S017 <= x:23.4,y:-19.05;
	PositionEntry( 0.0, -19.05, 0.0, 0.0, 0.0, 0.0 ), // S018 <= x:0,y:-19.05;
	PositionEntry( 99.6, -37.1, 0.0, 0.0, 0.0, 0.0 ), // S022 <= x:99.6,y:-37.1;
	PositionEntry( 80.55, -36.1, 0.0, 0.0, 0.0, 0.0 ), // S023 <= x:80.55,y:-36.1;
	PositionEntry( 61.5, -34.1, 0.0, 0.0, 0.0, 0.0 ), // S024 <= x:61.5,y:-34.1;
	PositionEntry( 42.45, -35.1, 0.0, 0.0, 0.0, 0.0 ), // S025 <= x:42.45,y:-35.1;
	PositionEntry( 23.4, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S026 <= x:23.4,y:-38.1;
	PositionEntry( 0.0, -38.1, 0.0, 0.0, 0.0, 0.0 ), // S027 <= x:0,y:-38.1;
	PositionEntry( 154.95, -75.05, 0.0, 0.0, 0.0, 0.0 ), // S028 <= x:154.95,y:-75.05;
	PositionEntry( 138.65, -68.05, 0.0, 0.0, 0.0, 0.0 ), // S029 <= x:138.65,y:-68.05;
	PositionEntry( 118.65, -51.05, 0.0, 0.0, 0.0, 0.0 ), // S030 <= x:118.65,y:-51.05;
	PositionEntry( 99.6, -56.15, 0.0, 0.0, 0.0, 0.0 ), // S031 <= x:99.6,y:-56.15;
	PositionEntry( 80.55, -55.15, 0.0, 0.0, 0.0, 0.0 ), // S032 <= x:80.55,y:-55.15;
	PositionEntry( 61.5, -53.15, 0.0, 0.0, 0.0, 0.0 ), // S033 <= x:61.5,y:-53.15;
	PositionEntry( 42.45, -54.15, 0.0, 0.0, 0.0, 0.0 ), // S034 <= x:42.45,y:-54.15;
	PositionEntry( 23.4, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S035 <= x:23.4,y:-57.15;
	PositionEntry( 0.0, -57.15, 0.0, 0.0, 0.0, 0.0 ), // S036 <= x:0,y:-57.15;
	PositionEntry( 147.0, -91.2, 0.0, 0.0, 0.0, 0.0 ), // S037 <= x:147,y:-91.2;
	PositionEntry( 139.8, -109.2, 0.0, 0.0, 0.0, 0.0 ), // S038 <= x:139.8,y:-109.2;
	PositionEntry( 126.4, -93.2, 0.0, 0.0, 0.0, 0.0 ), // S039 <= x:126.4,y:-93.2;
	PositionEntry( 109.1, -86.2, 0.0, 0.0, 0.0, 0.0 ), // S040 <= x:109.1,y:-86.2;
	PositionEntry( 80.55, -74.2, 0.0, 0.0, 0.0, 0.0 ), // S041 <= x:80.55,y:-74.2;
	PositionEntry( 61.5, -72.2, 0.0, 0.0, 0.0, 0.0 ), // S042 <= x:61.5,y:-72.2;
	PositionEntry( 42.45, -73.2, 0.0, 0.0, 0.0, 0.0 ), // S043 <= x:42.45,y:-73.2;
	PositionEntry( 23.4, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S044 <= x:23.4,y:-76.2;
	PositionEntry( 5.0, -76.2, 0.0, 0.0, 0.0, 0.0 ), // S045 <= x:5,y:-76.2;
};

